  version: '3.9'
  
  services:
    rabbitmq:
      image: rabbitmq:management
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - microservices
    
    user-service:
      build:
        context: .
        dockerfile: UserService/Dockerfile
      ports:
        - "5000:80"
      depends_on:
        - rabbitmq
      networks:
        - microservices
  
  networks:
    microservices:
      driver: bridge