services:
  user-service:
    build: ./UserService
    ports:
      - "5000:80"
    networks:
      - microservices

  product-service:
    build: ./ProductService
    ports:
      - "5001:80"
    depends_on:
      - user-service
    networks:
      - microservices

networks:
  microservices:
    driver: bridge