services:
  product-db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ProductDB
    ports:
      - "5432:5432"

  product-service:
    build: ./ProductService
    environment:
      ConnectionStrings__DefaultConnection: "Host=product-db;Database=ProductDB;Username=postgres;Password=postgres"
      UserService__BaseUrl: "http://user-service:5000"
    ports:
      - "5001:80"
    depends_on:
      - product-db