version: '3.9'

services:
  user-service:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - user-db

  user-db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: UserServiceDb
    ports:
      - "5432:5432"